spring:
  data:
    elasticSearch:
      host: localhost
      port: 9200
      cluster-name: elasticsearch
      cluster-nodes: localhost:9300
      client:
        connectNum: 10
        connectPerRoute: 50
